image: ruby:2.1

variables:
  LANG: "C.UTF-8"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: "1"

stages:
  - build
  - test

build:
  stage: build
  script:
    - bundler
    - gem install rake

test:
  stage: test
  script:
    - bundle exec rake test
  artifacts:
    paths:
    - _site

