variables:
  LANG: "C.UTF-8"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: "1"

stages:
  - build
  - test
  - publish

build:
  tags:
    - as8365
  stage: build
  image: jekyll/jekyll:4.2.0
  script:
    - rake build
    - echo "$CI_JOB_ID" > output/build.txt
  artifacts:
    paths:
      - output

test:
  tags:
    - as8365
  stage: test
  image: 18fgsa/html-proofer:gitlab-ci
  allow_failure: true
  script:
    - htmlproofer --url_ignore "/http(s?):\/\/(.*)\.ffda/, /^http:\/\/192\.168\..*/" --assume_extension ./output

publish:
  tags:
    - as8365
  stage: publish
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - curl $DEPLOY_URL?$(cat output/build.txt)

