image: ruby:2.4

variables:
  LANG: "C.UTF-8"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: "1"

before_script:
  - bundle install

stages:
  - build
  - test

build:
  stage: build
  script:
    - bundle exec rake build

test:
  stage: test
  script:
    - bundle exec rake test
  artifacts:
    paths:
    - _site

