variables:
  LANG: "C.UTF-8"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: "1"

stages:
  - build
  - test
  - publish

build:
  stage: build
  image: jekyll/jekyll:latest
  cache:
    key: $CI_COMMIT_SHA
    policy: push
    paths:
      - output
      - publish
  script:
    - jekyll build -d output
  after_script:
    - mkdir publish
    - echo $CI_JOB_ID > publish/build_job_id
  artifacts:
    paths:
    - output

test:
  stage: test
  image: 18fgsa/html-proofer:gitlab-ci
  allow_failure: true
  cache:
    key: $CI_COMMIT_SHA
    policy: pull
    paths:
      - output/
  script:
    - htmlproofer ./output

publish:
  stage: publish
  image: appropriate/curl:latest
  cache:
    key: $CI_COMMIT_SHA
    policy: pull
    paths:
      - publish/
  only:
    - master
  script:
    - curl $DEPLOY_URL?$(cat publish/build_job_id)

